const homeSecTwoTitle = 'Justo petentium te vix, scripta regione urbanitas';

const homeSecTwoText = 'Suspendisse vel nisi id odio consequat aliquam quis ac nisl. Vestibulum orci enim, porta viverra egestas laoreet, sollicitudin et orci. Ut id lacinia tortor. Sed et sollicitudin diam, sed facilisis eros. Donec sit amet consequat neque. Donec tristique tincidunt mi sed tincidunt. Suspendisse quis augue eget quam ullamcorper ultricies sed non justo.';

const homeSecThreeTitle = 'Nulla sem urna, dictum sed nisi in, viverra rutrum neque';

const homeSecThreeText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra nisi et massa rhoncus egestas. Ut eget lacus at urna ultricies ultrices eu vitae nisl. Cras vulputate faucibus sem. Nullam sodales dui lorem, laoreet ultricies orci eleifend nec. Suspendisse ornare sem eu ligula ornare ultrices. Quisque tincidunt quam sed nisl volutpat, ut ullamcorper nulla tempor. Integer sed aliquet ipsum. Nullam nec erat posuere, sagittis magna quis, euismod velit. Nulla maximus rutrum felis.';

const homeSecFourTitle = 'Sed libero justo, lobortis sit amet suscipit non';

const homeSecFourSubtitle = 'taria duo ut vis semper abhorreant';

const homeSecFourP1 = 'Pellentesque ac condimentum felis. Suspendisse vel suscipit dolor, nec laoreet nulla, Nam auctor ultricies dapibus. Donec ac interdum dul, quis finibus lectus. Cras in ultrices neque. Curabitur eget turpis iaculis diam congue sagittis a vel ligula. Mauris ut arcu ex. Nullam quis orci ante, Nunc felis massa, posuere non gravida in, commodo in arcu. in feugiat magna non volutpat faucibus. Nam aliquam justo nec aliquam iaculis. Integer laoreet pulvinar elt pulvinar fermentum. Morbi vehicula sodales nunc ac varius. Proin porttitor porttitor libero vel pharetra';

const homeSecFourP2 = 'Cras sit amet dapibus magna, Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec magnis dis parturient mantes, nascetur ridiculus mus Donec finibus nulla quis lorem mcllis lacinia Fusce ut arcu ligula Pellentesque augue ex, pellentesque ut maximus nan, eleifend ut lorem. Vestibulum rutrum malesuada turpis, molestie mattis uelit maximus ac Quisque iaculis hendrerit ex et tincidunt. Aenean eu magna ut nisi placerat fringilla in sed diam. Suspendisse tristique vel dui nec imperdiet. Cras mattis ligula quis fermentum suscipit Proin et elementum arcu, sit amet porttitor diam Curabitur euismod, eratvitae tristique volutpat, augue lectus dignissim justo, at faucibus orri est a elit. Sed sed sapien pretium, maximus felis vel, mollis elit.';

const homeSecFourP3 = 'Sed libero justo, lobortis sit amet suscipit nan, auctor non libero. Maecenas quis nisl eget enim porta blandit a nec sapien. Mauris porttitor lorem ut egestas euismccl Donec molestie tempor nibh, nec uenenatis arcu ullamccrper sit amet Nulla facilisL Proin cursus neque ut tortor scelerisque, at iaculis nunc ornare. Pellentesque non nunc nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus, Aenean et scdales diatn Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce porttitor magna augue, non auctor quam placerat nec. Nulla sem urna, dictum sed nisi in, viverra rutrum negue. Aliquam ipsum nunc, porta a augue nec, fringilla mollis arcu. In a vehicula odio. Praesent uulputate turpis eleifend egestas ultrices. Sed sed sapien pretium, maximus felis vel, maximus felis vel, mollis elit. Proin nec sagittis nibh. Curabitur fringilla felis a porttitor maxims Vestibulum aliquet ante nec leo malesuada porttitor sit amet et magna.';

export { homeSecTwoTitle, homeSecTwoText, homeSecThreeTitle, homeSecThreeText, homeSecFourTitle, homeSecFourSubtitle, homeSecFourP1, homeSecFourP2, homeSecFourP3 };