const topLine = 'Populo facilisi nam no, dolor deleniti deseruisse ne cum, nam quodsi aliquam eligendi ne. Ferri euismod accusata te nec, summo accumsan at vix.';

const paragraphOne = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pulvinar enim sed quam efficitur finibus. Fusce efficitur condimentum orci in hendrerit. Etiam aliquam vitae ante et scelerisque. Pellentesque commodo felis metus, nec congue nisi facilisis quis. Aenean maximus bibendum congue. Nulla pretium elit non facilisis imperdiet. Curabitur auctor lacus turpis, quis fringilla quam faucibus sed. Sed consequat magna enim, eu efficitur purus viverra sit amet. Praesent varius porta blandit mollis, felis ut convallis convallis.';

const paragraphTwo = 'Quisque non lectus dolor. In id dictum ex. Aenean laoreet velit sem, in dictum orci cursus sit amet. Duis ex est, aliquam quis tincidunt ut, imperdiet a lacus. Vestibulum condimentum vehicula nisl, at vestibulum velit varius sit amet. Cras lacinia facilisis tempus. Fusce nec tempus mauris. Sed vitae diam porta, tincidunt orci ac, maximus enim. Integer sodales sodales turpis, sit amet ultricies arcu lacinia id. Pellentesque volutpat in massa sit amet venenatis. Aliquam erat volutpat. Sed mollis, felis ut convallis convallis, nibh quam fringilla metus, a tempus metus nunc a sem. Morbi ut metus tincidunt, mollis orci quis, efficitur nibh.'

const paragraphThree = 'Integer ullamcorper nisi non ultricies consequat. Mauris at ipsum vel erat fringilla placerat ut eget nibh. Mauris vehicula a lectus dignissim ultrices. Sed congue nec libero sit amet vestibulum. Donec dignissim nec ligula quis placerat. Vivamus porttitor sed urna nec semper. Cras bibendum, est vitae placerat ultricies, diam massa congue magna, quis blandit nibh ante vitae nibh. Aliquam eu lobortis augue, eu vestibulum lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a ligula vitae nisl blandit tempus ut sit amet urna. Mauris convallis nisl a interdum semper. Fusce interdum ullamcorper purus sed aliquam. Fusce ut mollis nisi, quis lacinia quam. Donec ligula metus, volutpat a odio euismod, dapibus iaculis arcu. Ut lobortis magna vehicula laoreet feugiat. '

const paragraphFour = 'Suspendisse vel nisi id odio consequat aliquam quis ac nisl. Vestibulum orci enim, porta viverra egestas laoreet, sollicitudin et orci. Ut id lacinia tortor. Sed et sollicitudin diam, sed facilisis eros. Donec sit amet consequat neque. Donec tristique tincidunt mi sed tincidunt. Suspendisse quis augue eget quam ullamcorper ultricies sed non justo.'

const paragraphFive = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra nisi et massa rhoncus egestas. Ut eget lacus at urna ultricies ultrices eu vitae nisl. Cras vulputate faucibus sem. Nullam sodales dui lorem, laoreet ultricies orci eleifend nec. Suspendisse ornare sem eu ligula ornare ultrices. Quisque tincidunt quam sed nisl volutpat, ut ullamcorper nulla tempor. Integer sed aliquet ipsum. Nullam nec erat posuere, sagittis magna quis, euismod velit. Nulla maximus rutrum felis. Suspendisse maximus sodales lectus, quis condimentum arcu commodo sed. Aenean nec auctor neque, nec bibendum eros. Nulla blandit cursus ante, et posuere orci aliquam vel. Ut vel arcu sed lacus tristique malesuada.';

export { topLine, paragraphOne, paragraphTwo, paragraphThree, paragraphFour, paragraphFive };